### ISSUE TITLE
Broken TF Tree

### ISSUE THREAD

**Issue by dringakn** [ctu-mrs/simulation#13]
Hi,
I was running the one_drone_gps tmux script and exploring the tf tree. 
I found the tf_tree as broken. Attached here within is a snap shot of the tf tree. 

![one_drone_gps_tf_tree](https://user-images.githubusercontent.com/16977376/89409045-52b57780-d719-11ea-8d8d-793fafd838ff.png)

Could you point out what could be the possible reason?

**Comment by petrlmat** [comment]
Hi,
what do you mean by broken? Do you mean that the tree is not connected? It is like this, because the unconnected components are reference frames published by mavros, not us. All our frames are namespaced by the uav name, e.g., `uav1`. Our system is not dependent on the mavros reference frames.

**Comment by dringakn** [comment]
Yes, by broken I mean the tree was not connected. 
What is the purpose of odom_ned, base_link_frd to map_ned frames?
How can i refer the /uav1/fcu and /uav2/fcu within /map frame?

**Comment by spurnvoj** [comment]
> What is the purpose of odom_ned, base_link_frd and map_ned frames?

These frames are internally used in some of mavros plugins (see https://github.com/mavlink/mavros/issues/1162). They are planning to get rid of them.

> How can i refer the /uav1/fcu and /uav2/fcu within /map frame?

As @petrlmat mentioned, we are not using mavros frames at all. We are building an independent tree that is correctly connected (as you can see in your image of tf tree). Regarding the connection of trees of two different UAV, you have to create a new connection point (node) that will connect for example gps_origin frames. See our readme https://ctu-mrs.github.io/docs/system/frames_of_reference.html#multi-uav-tf-tree how to do that.
