### ISSUE TITLE
PX4 Firmware compile error

### ISSUE THREAD

**Issue by maxhofidrone** [ctu-mrs/simulation#23]
Hi,
I was trying to compile your tweaked PX firmware version according your [wiki page.](https://ctu-mrs.github.io/docs/hardware/px4_firmware.html) Unfortunately, `make px4_fmu-v5_default` fails with following response:
`../../platforms/common/include/px4_platform_common/atomic.h:169:34: error: parameter 'expected' set but not used [-Werror=unused-but-set-parameter]` 
You can find the whole terminal output here:
[error_msgs.txt](https://github.com/ctu-mrs/simulation/files/5905171/error_msgs.txt)
I updated the simulation package before and also tried it once with cloning the your PX4 fork directly.

Do you have any solution for this? 

Best regards,
Max

**Comment by klaxalk** [comment]
Hey, I have not seen this error yet. Make sure that:
1. you are building the right branch, currently, that is **1.11.2**, I am not sure about the state of the older branches.
2. all the submodules of *px4_firmware* are up to date (```git submodule update --init --recursive```)
3. you followed instructions on the original [site](https://docs.px4.io/master/en/dev_setup/building_px4.html) regarding the dependencies for cross-compiling it for your particular platform. If you want to build it for the original Pixhawk embedded hardware, that would require running
```bash
bash ./Tools/setup/ubuntu.sh
```
within the px4_firmware repository.

![Selection_161](https://user-images.githubusercontent.com/1611176/106497457-5bb3b580-64be-11eb-9026-cc16abda20fa.png)

Just tested it and it works fine. Let me know if problems persist.

Sincerely, Tomas

**Comment by maxhofidrone** [comment]
Hi @klaxalk,
thanks for your comment. I tried all the steps you mentioned- but unfortunately it did not help. But I found a solution [here](https://github.com/PX4/PX4-Autopilot/issues/15712). Uncommenting the `-Werror` option in `cmake/px4_add_common_flags.cmake` helped to finish the compilation without error. The former errors were now "only" warnings.
So I think this is a PX4 related issue right? 

Best regards,

Max

**Comment by klaxalk** [comment]
Hey, ye this is interesting. I don't know why this does not happen all the time. Maybe it is platform-specific. Anyway, this is a PX4-related issue, we don't do anything special here, just compilating the code (albeit with minor modifications) as it is intended by its authors. Thanks for finding the solution.

Sincerely
Tomas

**Comment by maxhofidrone** [comment]
Yes it happened for me (Ubuntu 18.04) also with the original PX4 stack before uncommenting this line.
