### ISSUE TITLE
zsh history

### ISSUE THREAD

**Issue by frapit** [ctu-mrs/simulation#28]
Small issue for `zsh` users out there, who are wondering why their `.zsh_history` always gets deleted after session start. In the tmuxinator example files the gazebo service is adding some command to the history:
```
- waitForOdometry; gz camera -c gzclient_camera -f uav1; history -s gz camera -c gzclient_camera -f uav1
```
As `history -s` is not available in zsh and there is some `-c` later in the line it gets parsed as `history -c` causing the history to be deleted. Maybe you could add a small hint to the docs.

**Comment by klaxalk** [comment]
I recommend adding this alias
```bash
# alias the "bash's" command history to "zshell's" command read
# handy for common tmuxinator scripts
historyRead() {
  eval 'print $@'
}
alias history='historyRead'
```

To your .zshrc. This will make zsh's history behave the same way as bash's.
