### ISSUE TITLE
cant spawn drones

### ISSUE THREAD

**Issue by MvB12** [ctu-mrs/simulation#30]
I'm attempting to complete the leader_follower_task. I, ve followed all the things mentioned in the packages but for some reason, drones aren't spawning in the gazebo. Initially, I could spawn them outside of tmux (ros launching the nodes simulation. launch, drone spawner, and calling service in separate terminals) but after deleting and freshly installing everything this stopped too and started to give the same error as in tmux. I've attached the log files and error images
![Screenshot from 2022-03-14 02-29-51](https://user-images.githubusercontent.com/41923680/158995222-0bcc17d9-1fcb-474c-aebd-6d0e785de2e7.png)
![Screenshot from 2022-03-17 03-03-46](https://user-images.githubusercontent.com/41923680/158995230-550789ea-9f75-4d0f-b9bf-10ebc1556c02.png)

[ui.zip](https://github.com/ctu-mrs/simulation/files/8304087/ui.zip)
.

**Comment by klaxalk** [comment]
Hey, it is hard to tell from the logs you sent. It is possible that some parts of the system did not survive the update well. I just tested it with my up-to-date system and it flies correctly. To simplify the process, could I ask you to test the leader-follower-task using our new [Singularity](https://github.com/ctu-mrs/mrs_singularity/) container? It should simplify the process for you immensely and provide a more 'reliable' long-term installation. Installing Singularity is also much faster and more reliable than installing our system "from scratch" natively into your OS. We spend a lot of time making the container as user-friendly as possible (no need to learn anything sophisticated).
