### ISSUE TITLE
Reg : Realsense Support in MRS simulation

### ISSUE THREAD

**Issue by dummyjohn77** [ctu-mrs/simulation#36]
Hi,

I was attempting to use the realsense binaries such as rs-pointcloud, rs-depth etc. 
The primary aim was to use the launch files from https://github.com/ctu-mrs/realsense and  https://github.com/IntelRealSense/realsense-ros to convert and use the depth clouds created by the realsense.

The realsense within the mrs-simulation is not detected by the system and thus I was not able to figure out the port configurations of the same (port is needed by the launch files in https://github.com/IntelRealSense/realsense-ros). 

Is it possible to use the realsense binaries in the simulation? If so, would it please be possible to share the steps required for the same?

Thanks

**Comment by petrapa6** [comment]
There's no need to use the `realsense-ros` package in our simulation. If you spawn a UAV with a realsense sensor (e.g., using `--enable-realsense-front` in [the drone spawner command](https://ctu-mrs.github.io/docs/simulation/drone_spawner.html#spawning-a-drone)), the simulation will publish the topics characteristic for the topics published by `realsense-ros`. 

For example, running the above option gives me topics `/*/front_rgbd/*` topics, including the depth on `/*/front_rgbd/aligned_depth_to_color/image_raw`. If you need to convert depth to point cloud, you have to convert it yourself or you may use [depth_image_proc](http://wiki.ros.org/depth_image_proc).

**Comment by dummyjohn77** [comment]
Thank you for the helpful and insightful inputs. This was really helpful.
