### ISSUE TITLE
Error while building px4 package

### ISSUE THREAD

**Issue by JuSquare** [ctu-mrs/simulation#7]
Hi,

While building the px4 package, I get the following error: 

Errors     << px4:make /home/julien/mrs2020_ws/logs/px4/build.make.002.log                                                                                                                                        
/home/julien/mrs2020_ws/src/simulation/ros_packages/px4/src/modules/commander/PreflightCheck.cpp: In function ‘bool Preflight::preflightCheck(void**, vehicle_status_s&, vehicle_status_flags_s&, bool, bool, bool, const hrt_abstime&)’:
/home/julien/mrs2020_ws/src/simulation/ros_packages/px4/src/modules/commander/PreflightCheck.cpp:716:6: error: ‘__builtin___sprintf_chk’ may write a terminating nul past the end of the destination [-Werror=format-overflow=]
 bool preflightCheck(orb_advert_t *mavlink_log_pub, vehicle_status_s &status, vehicle_status_flags_s &status_flags,
      ^~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [src/modules/commander/commander_tests/CMakeFiles/modules__commander__commander_tests.dir/__/PreflightCheck.cpp.o] Error 1
make[1]: *** [src/modules/commander/commander_tests/CMakeFiles/modules__commander__commander_tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/julien/mrs2020_ws/src/simulation/ros_packages/px4/src/modules/mavlink/mavlink_tests/mavlink_ftp_test.cpp: In static member function ‘static void MavlinkFtpTest::receive_message_handler_burst(const mavlink_file_transfer_protocol_t*, void*)’:
/home/julien/mrs2020_ws/src/simulation/ros_packages/px4/src/modules/mavlink/mavlink_tests/mavlink_ftp_test.cpp:851:41: error: ‘reply’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   ut_compare("Offset incorrect", reply->offset, full_packet_bytes);
                                         ^~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [src/modules/mavlink/mavlink_tests/CMakeFiles/modules__mavlink__mavlink_tests.dir/mavlink_ftp_test.cpp.o] Error 1
make[1]: *** [src/modules/mavlink/mavlink_tests/CMakeFiles/modules__mavlink__mavlink_tests.dir/all] Error 2
make: *** [all] Error 2
cd /home/julien/mrs2020_ws/build/px4; catkin build --get-env px4 | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -

Is this a known issue? Or maybe I made sthg wrong. 
By the way, all other packages were successfully built (uav_core ros_packages + mavlink_sitl_gazebo, and mrs_gazebo_common_resources), although some of them yielded warnings (which I can provide if necessary).

Thank you for your help!
Julien

**Comment by spurnvoj** [comment]
Hi Julien, how did you install the simulation? It was installed as part of the complete [mrs_uav_system](https://github.com/ctu-mrs/mrs_uav_system) or independently? if independently, did you call install dependencies as is written in the [README](https://github.com/ctu-mrs/simulation#installing-simulation). The simulation should not have any warnings, so could you post here output from the terminal.

**Comment by JuSquare** [comment]
Hi Vojtech,

Since I already have ROS installed, I decided to install all packages by myself. To do so, I followed the steps provided in UAV_CORE and SIMULATION. In the UAV_CORE. 

I commented out the "general" dependencies installation lines in the installation/install.sh. This was necessary because of the "sudo apt install -y gcc-arm-none-eabi" which results in dpkg-deb error (broken pipe). However, this did not yield issues when building the MRS ROS packages.

I re-built the packages, there is not warning anymore, but the px4 package still fails and exits with code 2. 

Note that running the simulation/installation/install.sh leads to the following error when installin PX4 Python3 dependencies: 
- ERROR: launchpadlib 1.10.6 requires testresources, which is not installed.
- ERROR: tensorboard 2.1.1 has requirement google-auth<2,>=1.6.3, but you'll have google-auth 1.4.2 which is incompatible.
- ERROR: google-colab 1.0.0 has requirement ipykernel~=4.6.0, but you'll have ipykernel 5.2.1 which is incompatible.
Installing testresources solved this issue. 

I am using Ubuntu 18.04.4 LTS Bionic with ROS Melodic.

**Comment by spurnvoj** [comment]
Our system is tested every time after a new commit by Travis CI. Therefore we will know if the packages are broken. The install script works on freshly installed ubuntu, as you can see [here](https://travis-ci.com/github/ctu-mrs/simulation). So this is specific to your setup. 

Try to find some advice in the original repository for [Firmware](https://github.com/PX4/Firmware). We have changed the original version only lightly, so If you manage to build the original one, you should be able to build our version.

**Comment by JuSquare** [comment]
Ok I'll try another way.
Thank you for your support.

**Comment by mkrizmancic** [comment]
Hi @JuSquare,

I have the exact same errors as in your first question (also using Ubuntu 18.04. and ROS Melodic). I didn't have any issues with installing PX4 Python 3 dependencies though. Also, I couldn't find anything related to this in the original repository.

Did you perhaps find a solution? Or do you at least have any more info that could help narrow down the cause?
